import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Container from "@/components/layout/Container";
import type { Metadata } from "next";
import AudioWrapper from "@/components/store/AudioWrapper";
import GlobalAudioShell from "@/components/audioplayer/GlobalAudioShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <AudioWrapper>  
    <Container>
      <Header />
      <div className="flex-grow">
        {children}
      </div>
      <GlobalAudioShell />
      <Footer />
    </Container>
  </AudioWrapper>
  );
}
