import "./globals.css";
import Footer from "@/components/layout/Footer";
import Container from "@/components/layout/Container";
import type { Metadata } from "next";
import GlobalAudioShell from "@/components/audioplayer/GlobalAudioShell";
import AudioContextProvider from "@/components/audioplayer/AudioContextProvider";
import CookiesBar from "@/components/cookies/CookiesBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AudioContextProvider>
      <Container>
        <div className="flex-grow">
          {children}
        </div>
        <GlobalAudioShell />
        <Footer />
        <CookiesBar />
      </Container>
    </AudioContextProvider>
  );
}
